#!/bin/bash
# Quick examples for results_to_latex.py

echo "🎨 MAHILDA Results to LaTeX - Quick Examples"
echo ""
echo "=== SUMMARY (fastest) ==="
echo "python3 results_to_latex.py --summary -o mahilda_summary.tex"
echo ""
echo "=== TOP 10 RULES (most common) ==="
echo "python3 results_to_latex.py --top 10 -o mahilda_top10.tex"
echo ""
echo "=== TOP 20 RULES ==="
echo "python3 results_to_latex.py --top 20 -o mahilda_top20.tex"
echo ""
echo "=== COMPLETE REPORT ==="
echo "python3 results_to_latex.py --all -o mahilda_complete.tex"
echo ""
echo "=== SORTED BY CONFIDENCE ==="
echo "python3 results_to_latex.py --metric confidence -o mahilda_conf.tex"
echo ""
echo "=== SORTED BY SUPPORT ==="
echo "python3 results_to_latex.py --metric support -o mahilda_support.tex"
echo ""
echo "=== LONG TABLES (for multi-page PDFs) ==="
echo "python3 results_to_latex.py --format longtable --all -o mahilda_long.tex"
echo ""
echo "=== WITH PDF COMPILATION ==="
echo "python3 results_to_latex.py --all --compile -o mahilda_results.tex"
echo ""
echo "=== CUSTOM RESULTS DIRECTORY ==="
echo "python3 results_to_latex.py --results-dir /path/to/results -o output.tex"
echo ""
echo "=== ALL OPTIONS ==="
echo "python3 results_to_latex.py --help"
