#!/bin/bash
# Quick examples for results_to_latex.py

echo "🎨 MARITA Results to LaTeX - Quick Examples"
echo ""
echo "=== SUMMARY (fastest) ==="
echo "python3 research/legacy/results_to_latex.py --summary -o research/generated/marita_summary.tex"
echo ""
echo "=== TOP 10 RULES (most common) ==="
echo "python3 research/legacy/results_to_latex.py --top 10 -o research/generated/marita_top10.tex"
echo ""
echo "=== TOP 20 RULES ==="
echo "python3 research/legacy/results_to_latex.py --top 20 -o research/generated/marita_top20.tex"
echo ""
echo "=== COMPLETE REPORT ==="
echo "python3 research/legacy/results_to_latex.py --all -o research/generated/marita_complete.tex"
echo ""
echo "=== SORTED BY CONFIDENCE ==="
echo "python3 research/legacy/results_to_latex.py --metric confidence -o research/generated/marita_conf.tex"
echo ""
echo "=== SORTED BY SUPPORT ==="
echo "python3 research/legacy/results_to_latex.py --metric support -o research/generated/marita_support.tex"
echo ""
echo "=== LONG TABLES (for multi-page PDFs) ==="
echo "python3 research/legacy/results_to_latex.py --format longtable --all -o research/generated/marita_long.tex"
echo ""
echo "=== WITH PDF COMPILATION ==="
echo "python3 research/legacy/results_to_latex.py --all --compile -o research/generated/marita_results.tex"
echo ""
echo "=== CUSTOM RESULTS DIRECTORY ==="
echo "python3 research/legacy/results_to_latex.py --results-dir /path/to/results -o research/generated/output.tex"
echo ""
echo "=== ALL OPTIONS ==="
echo "python3 research/legacy/results_to_latex.py --help"
